global:
  scrape_interval: 15s

scrape_configs:
  # Self-scraping for Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape configuration for the OpenTelemetry Collector's Prometheus exporter
  - job_name: 'otel-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'fdb_.*'
        action: keep