logger:
  enabled: true
  environment: development
  level: info

mdbx:
  enabled: true
  nodes:
    - name: fdb
      path: /tmp/
      maxReaders: 4096
      maxSize: 1024            # Maximum database size (1 TB)
      minSize: 1               # Minimum database size (1 GB)
      growthStep: 4096         # Growth step size (4 KB)
      filePermissions: 0600    # File permissions for the database

# ======================================================================================
# P2P NETWORKING RELATED CONFIGURATION
# ======================================================================================
networking:
  peerId: "12D3KooWNCXC8gZFxvcjpFGhjcdFndkTs7k7RnanB9mxwWkNXuWx"
  listenAddrs:  # Changed from single port to multiple listen addresses
    - "/ip4/0.0.0.0/tcp/8432"               # Listen on all TCP IPv4 interfaces
    - "/ip6/::/tcp/8432"                    # Listen on all TCP IPv6 interfaces
    - "/ip4/0.0.0.0/udp/8432"               # Listen on all UDP IPv4 interfaces
    - "/ip6/::/udp/8432"                    # Listen on all UDP IPv6 interfaces
  protocolId: "/fdb/1.0.0"             # Unique protocol identifier
  bootstrapPeers:
    - /ip4/127.0.0.1/tcp/8432/p2p/12D3KooWNCXC8gZFxvcjpFGhjcdFndkTs7k7RnanB9mxwWkNXuWx # For bootstrap node it is here but will be ignored
  bootstrapNode: true                        # Set to true if this node is the bootstrap node in the network.
  mdns: true                                 # Enable or disable Multicast DNS (mDNS) discovery.
  enableRelay: true                          # Enable relay connections if needed.
  interface_name: "enp73s0"                  # Network interface name for eBPF (if applicable)

pprof:
  - name: fdb
    enabled: true
    addr: "127.0.0.1:4060"

transports:
  - type: dummy
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 4434

  - type: quic
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 4433
      tls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem

  - type: uds
    enabled: true
    config:
      socket: "/tmp/fdb.sock"

  - type: tcp
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 5011
      tls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem

  - type: udp
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 5022
      dtls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem