# ======================================================================================
# NODE IDENTITY RELATED CONFIGURATIONS
# ======================================================================================
id: "peer_node_1"

# ======================================================================================
# LOGGER RELATED CONFIGURATIONS
# ======================================================================================
logger:
  enabled: true
  environment: development
  level: debug

# ======================================================================================
# MDBX RELATED CONFIGURATIONS
# ======================================================================================
mdbx:
  enabled: true
  nodes:
    - name: fdb
      path: /tmp/
      maxReaders: 4096
      maxSize: 1024            # Maximum database size (1 TB)
      minSize: 1               # Minimum database size (1 GB)
      growthStep: 4096         # Growth step size (4 KB)
      filePermissions: 0600    # File permissions for the database

# ======================================================================================
# NODE RELATED CONFIGURATION
# ======================================================================================
node:
  # In blockchain world there is full node, light node, sequencer, validator, etc...
  # This is practically the same concept have RBAC (Role-Based Access Control) and
  # that is how node types are defined. Reusing this system to not pollute the system with
  # multiple nodes and role types and making things even more confusing than it is.
  roles:
    - node


# ======================================================================================
# IDENTITY MANAGER RELATED CONFIGURATION
# ======================================================================================
# Identity manager is responsible for generating P2P, BLS, and other keys.
identity:
  enabled: true  # Enable or disable the identity manager.
  basePath: /Users/nevio/.fdb/keystore  # Path where keys are stored.

# ======================================================================================
# P2P NETWORKING RELATED CONFIGURATION
# ======================================================================================
networking:
  peerId: "12D3KooWJwvXTmBGQ5MeqVBwnU18WgUdAnJtZwuLKN2wasUVoiq3"
  listenAddrs:  # Changed from single port to multiple listen addresses
    - "/ip4/0.0.0.0/tcp/8433"               # Listen on all TCP IPv4 interfaces
    - "/ip6/::/tcp/8433"                    # Listen on all TCP IPv6 interfaces
    - "/ip4/0.0.0.0/udp/8433"               # Listen on all UDP IPv4 interfaces
    - "/ip6/::/udp/8433"                    # Listen on all UDP IPv6 interfaces
  protocolId: "/fdb/1.0.0"                  # Unique protocol identifier
  bootstrapPeers:
    - /ip4/127.0.0.1/tcp/8432/p2p/12D3KooWK2kJYjJZs23UCv9KqxNxgtu19xgipQsKbrXDsfsLestN # Connect to the first node
  bootstrapNode: false                       # This is a regular node, not a bootstrap node
  mdns: true                                 # Enable or disable Multicast DNS (mDNS) discovery.
  enableRelay: true                          # Enable relay connections if needed.
  interface_name: "en0"                      # Network interface name for eBPF (if applicable)

# ======================================================================================
# TRANSPORTS RELATED CONFIGURATIONS
# ======================================================================================
transports:
  - type: dummy
    enabled: false
    config:
      ipv4: 127.0.0.1
      port: 4434

  - type: quic
    enabled: false
    config:
      ipv4: 127.0.0.1
      port: 4433
      tls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem

  - type: uds
    enabled: false
    config:
      socket: "/tmp/fdb.sock"

  - type: tcp
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 5012
      tls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem

  - type: udp
    enabled: false
    config:
      ipv4: 127.0.0.1
      port: 5022
      dtls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem

# ======================================================================================
# RPC RELATED CONFIGURATIONS
# ======================================================================================
rpc:
  poolMaxSize: 10_000
  transport:
    enabled: true
    type: "tcp"
    ipv4: 0.0.0.0
    port: 8846

# ======================================================================================
# OBSERVABILITY CONFIGURATION (Metrics and Tracing)
# ======================================================================================
pprof:
  - name: fdb
    enabled: true
    addr: "0.0.0.0:6061"

# ======================================================================================
# OBSERVABILITY CONFIGURATION (Metrics and Tracing)
# ======================================================================================
# Observability helps in monitoring system health, performance, and errors.
# It includes metrics (Prometheus) and tracing (OpenTelemetry).
observability:
  metrics:
    enable: true  # Enable or disable metrics collection.
    endpoint: "localhost:4317"  # Endpoint for metrics collector.
    exportInterval: 15s  # Interval to export metrics data.
    useTLS: false  # Set this to false to disable TLS.

  tracing:
    enable: true  # Enable or disable tracing.
    endpoint: "localhost:4317"  # Endpoint for tracing collector.
    headers: {}  # Additional headers for tracing requests.
    sampler: "always_on"  # Options: always_on, probability.
    samplingRate: 0.1  # Sampling rate for probabilistic sampling.
    useTLS: false  # Set this to false to disable TLS.