logger:
  enabled: true
  environment: development
  level: info

mdbx:
  enabled: true
  nodes:
    - name: fdb
      path: /tmp/
      maxReaders: 4096
      maxSize: 1024            # Maximum database size (1 TB)
      minSize: 1               # Minimum database size (1 GB)
      growthStep: 4096         # Growth step size (4 KB)
      filePermissions: 0600    # File permissions for the database

pprof:
  - name: fdb
    enabled: true
    addr: "127.0.0.1:4060"

transports:
  - type: dummy
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 4434

  - type: quic
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 4433
      tls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem

  - type: uds
    enabled: true
    config:
      socket: "/tmp/fdb.sock"

  - type: tcp
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 5011
      tls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem

  - type: udp
    enabled: true
    config:
      ipv4: 127.0.0.1
      port: 5022
      dtls:
        insecure: true
        key: ./data/certs/key.pem
        cert: ./data/certs/cert.pem