// Code generated by capnpc-go. DO NOT EDIT.

package schema

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type Request capnp.Struct
type Request_get Request
type Request_set Request
type Request_delete Request
type Request_exists Request
type Request_Which uint16

const (
	Request_Which_get    Request_Which = 0
	Request_Which_set    Request_Which = 1
	Request_Which_delete Request_Which = 2
	Request_Which_exists Request_Which = 3
)

func (w Request_Which) String() string {
	const s = "getsetdeleteexists"
	switch w {
	case Request_Which_get:
		return s[0:3]
	case Request_Which_set:
		return s[3:6]
	case Request_Which_delete:
		return s[6:12]
	case Request_Which_exists:
		return s[12:18]

	}
	return "Request_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Request_TypeID is the unique identifier for the type Request.
const Request_TypeID = 0xca991a3b3da8e19c

func NewRequest(s *capnp.Segment) (Request, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return Request(st), err
}

func NewRootRequest(s *capnp.Segment) (Request, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return Request(st), err
}

func ReadRootRequest(msg *capnp.Message) (Request, error) {
	root, err := msg.Root()
	return Request(root.Struct()), err
}

func (s Request) String() string {
	str, _ := text.Marshal(0xca991a3b3da8e19c, capnp.Struct(s))
	return str
}

func (s Request) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Request) DecodeFromPtr(p capnp.Ptr) Request {
	return Request(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Request) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Request) Which() Request_Which {
	return Request_Which(capnp.Struct(s).Uint16(0))
}
func (s Request) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request) Get() Request_get { return Request_get(s) }

func (s Request) SetGet() {
	capnp.Struct(s).SetUint16(0, 0)
}

func (s Request_get) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_get) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_get) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_get) Key() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Request_get) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_get) SetKey(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Request) Set() Request_set { return Request_set(s) }

func (s Request) SetSet() {
	capnp.Struct(s).SetUint16(0, 1)
}

func (s Request_set) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_set) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_set) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_set) Key() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Request_set) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_set) SetKey(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Request_set) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Request_set) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Request_set) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s Request) Delete() Request_delete { return Request_delete(s) }

func (s Request) SetDelete() {
	capnp.Struct(s).SetUint16(0, 2)
}

func (s Request_delete) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_delete) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_delete) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_delete) Key() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Request_delete) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_delete) SetKey(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Request) Exists() Request_exists { return Request_exists(s) }

func (s Request) SetExists() {
	capnp.Struct(s).SetUint16(0, 3)
}

func (s Request_exists) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request_exists) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request_exists) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request_exists) Key() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Request_exists) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request_exists) SetKey(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Request_List is a list of Request.
type Request_List = capnp.StructList[Request]

// NewRequest creates a new list of Request.
func NewRequest_List(s *capnp.Segment, sz int32) (Request_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[Request](l), err
}

// Request_Future is a wrapper for a Request promised by a client call.
type Request_Future struct{ *capnp.Future }

func (f Request_Future) Struct() (Request, error) {
	p, err := f.Future.Ptr()
	return Request(p.Struct()), err
}
func (p Request_Future) Get() Request_get_Future { return Request_get_Future{p.Future} }

// Request_get_Future is a wrapper for a Request_get promised by a client call.
type Request_get_Future struct{ *capnp.Future }

func (f Request_get_Future) Struct() (Request_get, error) {
	p, err := f.Future.Ptr()
	return Request_get(p.Struct()), err
}
func (p Request_Future) Set() Request_set_Future { return Request_set_Future{p.Future} }

// Request_set_Future is a wrapper for a Request_set promised by a client call.
type Request_set_Future struct{ *capnp.Future }

func (f Request_set_Future) Struct() (Request_set, error) {
	p, err := f.Future.Ptr()
	return Request_set(p.Struct()), err
}
func (p Request_Future) Delete() Request_delete_Future { return Request_delete_Future{p.Future} }

// Request_delete_Future is a wrapper for a Request_delete promised by a client call.
type Request_delete_Future struct{ *capnp.Future }

func (f Request_delete_Future) Struct() (Request_delete, error) {
	p, err := f.Future.Ptr()
	return Request_delete(p.Struct()), err
}
func (p Request_Future) Exists() Request_exists_Future { return Request_exists_Future{p.Future} }

// Request_exists_Future is a wrapper for a Request_exists promised by a client call.
type Request_exists_Future struct{ *capnp.Future }

func (f Request_exists_Future) Struct() (Request_exists, error) {
	p, err := f.Future.Ptr()
	return Request_exists(p.Struct()), err
}

type Response capnp.Struct
type Response_get Response
type Response_set Response
type Response_delete Response
type Response_exists Response
type Response_error Response
type Response_Which uint16

const (
	Response_Which_get    Response_Which = 0
	Response_Which_set    Response_Which = 1
	Response_Which_delete Response_Which = 2
	Response_Which_exists Response_Which = 3
	Response_Which_error  Response_Which = 4
)

func (w Response_Which) String() string {
	const s = "getsetdeleteexistserror"
	switch w {
	case Response_Which_get:
		return s[0:3]
	case Response_Which_set:
		return s[3:6]
	case Response_Which_delete:
		return s[6:12]
	case Response_Which_exists:
		return s[12:18]
	case Response_Which_error:
		return s[18:23]

	}
	return "Response_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Response_TypeID is the unique identifier for the type Response.
const Response_TypeID = 0xc4b26ed94697ea43

func NewResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Response(st), err
}

func NewRootResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Response(st), err
}

func ReadRootResponse(msg *capnp.Message) (Response, error) {
	root, err := msg.Root()
	return Response(root.Struct()), err
}

func (s Response) String() string {
	str, _ := text.Marshal(0xc4b26ed94697ea43, capnp.Struct(s))
	return str
}

func (s Response) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Response) DecodeFromPtr(p capnp.Ptr) Response {
	return Response(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Response) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Response) Which() Response_Which {
	return Response_Which(capnp.Struct(s).Uint16(2))
}
func (s Response) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Response) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Response) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Response) Get() Response_get { return Response_get(s) }

func (s Response) SetGet() {
	capnp.Struct(s).SetUint16(2, 0)
}

func (s Response_get) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Response_get) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Response_get) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Response_get) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Response_get) HasValue() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Response_get) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Response_get) Exists() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Response_get) SetExists(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Response) Set() Response_set { return Response_set(s) }

func (s Response) SetSet() {
	capnp.Struct(s).SetUint16(2, 1)
}

func (s Response_set) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Response_set) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Response_set) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Response_set) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Response_set) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Response) Delete() Response_delete { return Response_delete(s) }

func (s Response) SetDelete() {
	capnp.Struct(s).SetUint16(2, 2)
}

func (s Response_delete) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Response_delete) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Response_delete) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Response_delete) Success() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Response_delete) SetSuccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Response) Exists() Response_exists { return Response_exists(s) }

func (s Response) SetExists() {
	capnp.Struct(s).SetUint16(2, 3)
}

func (s Response_exists) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Response_exists) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Response_exists) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Response_exists) Exists() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Response_exists) SetExists(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Response) Error() Response_error { return Response_error(s) }

func (s Response) SetError() {
	capnp.Struct(s).SetUint16(2, 4)
}

func (s Response_error) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Response_error) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Response_error) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Response_error) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Response_error) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Response_error) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Response_error) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Response_List is a list of Response.
type Response_List = capnp.StructList[Response]

// NewResponse creates a new list of Response.
func NewResponse_List(s *capnp.Segment, sz int32) (Response_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Response](l), err
}

// Response_Future is a wrapper for a Response promised by a client call.
type Response_Future struct{ *capnp.Future }

func (f Response_Future) Struct() (Response, error) {
	p, err := f.Future.Ptr()
	return Response(p.Struct()), err
}
func (p Response_Future) Get() Response_get_Future { return Response_get_Future{p.Future} }

// Response_get_Future is a wrapper for a Response_get promised by a client call.
type Response_get_Future struct{ *capnp.Future }

func (f Response_get_Future) Struct() (Response_get, error) {
	p, err := f.Future.Ptr()
	return Response_get(p.Struct()), err
}
func (p Response_Future) Set() Response_set_Future { return Response_set_Future{p.Future} }

// Response_set_Future is a wrapper for a Response_set promised by a client call.
type Response_set_Future struct{ *capnp.Future }

func (f Response_set_Future) Struct() (Response_set, error) {
	p, err := f.Future.Ptr()
	return Response_set(p.Struct()), err
}
func (p Response_Future) Delete() Response_delete_Future { return Response_delete_Future{p.Future} }

// Response_delete_Future is a wrapper for a Response_delete promised by a client call.
type Response_delete_Future struct{ *capnp.Future }

func (f Response_delete_Future) Struct() (Response_delete, error) {
	p, err := f.Future.Ptr()
	return Response_delete(p.Struct()), err
}
func (p Response_Future) Exists() Response_exists_Future { return Response_exists_Future{p.Future} }

// Response_exists_Future is a wrapper for a Response_exists promised by a client call.
type Response_exists_Future struct{ *capnp.Future }

func (f Response_exists_Future) Struct() (Response_exists, error) {
	p, err := f.Future.Ptr()
	return Response_exists(p.Struct()), err
}
func (p Response_Future) Error() Response_error_Future { return Response_error_Future{p.Future} }

// Response_error_Future is a wrapper for a Response_error promised by a client call.
type Response_error_Future struct{ *capnp.Future }

func (f Response_error_Future) Struct() (Response_error, error) {
	p, err := f.Future.Ptr()
	return Response_error(p.Struct()), err
}

const schema_d52c062bf4b48979 = "x\xda\xac\x94OHTQ\x14\xc6\xcf\xb9\xf7\xbe\x19\x03" +
	"\x1ft\x991(\x92\x01\x11RJG\x9d\\4j#" +
	"F\x81D\xd4+\x82p\xf7\x1c/S\xa4\xce4w\xac" +
	"\x0c\xa4\x88 ]\xd8N\xc2(\x8c\xa0\x7f\x9bH\xa9\x85" +
	"D\x8b\xa0\x82\x82\xc8\x84(\x17\x05\x11\x15\xd4\xa2M\x9b" +
	"(\xbbq\xdf8\xef5\xf2&\x1cj9\x87o~\xe7" +
	"|\xdf;\xf74}\xc0N\xd6lF\x0d V\xbb\x11" +
	"P\xcf\xec\xd7U\xa9\x03\xbb\xcf\x82\xb5\x01Q]|w" +
	"\xa3\xa3m\xdd\xe4S\xa8\"A\x04\x88\x8d\x90,\x02\x86" +
	"\xc6H\x02PMu\xdf\xbfrn\xf6r\x09\xe9M\xd2" +
	"\xa3\xa5w\xc91@5\xfdq\xcd\xf7\xb9\xd1K\xa3\xfe" +
	"RN\x1di5\xd5\xd4\xb6\xb1}F{\xed\x96q\xb0" +
	"\xea\x10\xd5\xb6\xcf\xe7w,\x0c\xce<\x84*t\xa4\x1d" +
	"\xb4WK\xbb\xa9\xa6N<\xcf\x89\xa9\x89\xb9k\xfe\xd2" +
	"\xaby\xe9\xb4Cm\xde\xf9\x80_8\xf5\xe5\xb6\xff\x00" +
	"/\xa8c\xeb\x8d#u9V\x04Q\x0d\x8f\xdd\xf9\xb6" +
	"1\xb0\xe9%l\xc7\xa0\x81\x18[\xa4]\x182Y\x10" +
	" \xb6\x8aE\x10P\xbd\xea\x99\x9f\xf9\xba>\xf0\xd8\x7f" +
	"\x8aqvB\xa3'\x99F\xbb}\x97\xa1I\x90\x01\xc4" +
	"fY\x1cCO4:\xf4\x88}\x02T\xb7\x02t\xeb" +
	"\xf5\xb7\xc3\x0b\xfe\xe4z\xc3\x19\xba\xd5\xd0\xe4\xd3\xef\xef" +
	"\xcdOv\x9eQ\xfe\xd2\xfd\x863\x84m$\xa0Ae" +
	"\xb2\xe9\\:\x99\xeeg2\x9a\xb43\x83Q\x99<(" +
	"\x06\xech_o\xa3\xfe\x99\x89\xef\x15G\x86\x84\xcc5" +
	"\x8a\xc8\xf1C2'-F\x19@\x18\x19\x007k\x00" +
	"\xac\x0a\x8aV\x98`\xf0\xb0\x18F\x13\x08\x9a\x80+f" +
	"J*rVE\x1e\x88\x00\xbc^\x03k)ZM\x04" +
	"9b\x18\x09\x00oh\x01\xb0\xea(Z\x9b\x8b\xbbD" +
	"\x8e\xda\xfdC\xa2\xec\x9e)\xdd\xd31\xc1\xf0\xdf<\xc8" +
	"LzP\x8a\xc6`\xaa`\xc2\x01\xd6\xb7x\x1e\xb4\x05" +
	"]k\x88{\x16\x8a\xc7N\x08'UD \x88eu" +
	"\x95\x05\x1b\xf9\x94\xcc.\xcf\xc7I9\x94L\x0aY\x0e" +
	"5\x9fM_D\xf4\x8b\x9c(p\xe9\xff\xc8\x07\xf6 " +
	"Za\xca*\x95\xc2?\x9e3\x1f\xa9\x01b\xe2/]" +
	"t\x1f.\x17\xbaH\x16u\xd1]a\xbe+\x0e\xc4\xa4" +
	"?u\xd1}\\\xbcU\x17\xd9\x0f]t\xdf\x05\xafn" +
	"\x01\xa2?\x87\x0e'\xd1\xe7xY\x0a8\"\xb2\xd9t" +
	"v\xe5\xf1.\xfd\xadh\xdb\xe3^\x12\xa5>\x1b-\xc5" +
	"M\xe4\x13\xd6Y\xac.d\xe1^An{Y\xb8W" +
	"\x94w{Y\xb8\xe7\x8a7{Y\xb8\xa7\x99\xaf\x8d\x97" +
	"\xb2\xbdr\xc3\xf9\x80\x0a~\x8d\xe5\x1b5 \xa4\xb4S" +
	"\x02+\x81`e9{\xba4O\xd1J\xfdeU\x7f" +
	"\x07\x00\x00\xff\xff\xf9$\xe0-"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d52c062bf4b48979,
		Nodes: []uint64{
			0x874f586715d861cd,
			0x87a0b98ea2bd499f,
			0x889d88d0f916e6b1,
			0x8d39243c0553893b,
			0xa6d0959f6574cf95,
			0xb0eb809a11c14b31,
			0xc4b26ed94697ea43,
			0xc6061cefb2d25ad7,
			0xca991a3b3da8e19c,
			0xd979dea73e0306ae,
			0xff844099d2bbe382,
		},
		Compressed: true,
	})
}
